require ("ethan.launch")
require ("ethan.options")
require ("ethan.keymaps")
require ("ethan.autocmds")

-- Plugins 
spec("ethan.colorscheme")
spec("ethan.devicons")
spec("ethan.treesitter")
spec("ethan.mason")
spec("ethan.schemastore")
spec("ethan.lspconfig")
spec("ethan.whichkey")
spec("ethan.jdtls")
spec("ethan.cmp")
spec ("ethan.none-ls")
spec ("ethan.telescope")
spec ("ethan.nvimtree")
spec("ethan.comment")
spec("ethan.lualine")
spec("ethan.navic")
spec("ethan.breadcrumbs")
spec("ethan.harpoon")
spec("ethan.tabby")
spec("ethan.neotab")
spec("ethan.gitsigns")
spec("ethan.autopairs")
spec("ethan.project")
spec("ethan.indentline")
spec("ethan.colorizer")
spec("ethan.tmux-navigator")
-- Plugins I am not sure I will continue to use
-- spec("ethan.illuminate")
-- spec ("ethan.oil")
-- spec ("ethan.ufo")
-- spec("ethan.neoscroll")
-- spec("ethan.lab")
-- spec("ethan.neotest")
require("ethan.lazy")
